apiVersion: v1
kind: Pod
metadata:
  name: wordphonemenode
  labels:
    app: node
  namespace: wordphoneme
spec:
  containers:
    - name: wordphonemenode
      image: ramkashyapch/wordphoneme-node
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: wordphoneme
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30009
  type: NodePort
